### ISSUE TITLE
Add a header section to the manifest

### ISSUE THREAD

**Issue by RKrahl** [RKrahl/archive-tools#16]
Add a dedicated header section with some metadata to the manifest. This could facilitate compatibility across versions. Could do this in a separate YAML document, so the result could look like:
```yaml
%YAML 1.1
---
Checksums:
- sha256
Date: Sun, 10 Mar 2019 12:40:26 +0100
Generator: archive-tools 1.0
Version: '1.0'
---
- gid: 100
  gname: users
  mode: 493
  mtime: 1413139698.2000918
  path: Bilder/2014
  type: d
  uid: 1000
  uname: rolf
```
